export const API_URL = 'http://localhost:5000';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGOUT_USER = 'LOGOUT_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';

export const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS';
export const UPLOAD_PICTURE_FAILURE = 'UPLOAD_PICTURE_FAILURE';
export const UPLOAD_PICTURE_REQUEST = 'UPLOAD_PICTURE_REQUEST';

export const DELETE_PICTURE_SUCCESS = 'DELETE_PICTURE_SUCCESS';
export const DELETE_PICTURE_FAILURE = 'DELETE_PICTURE_FAILURE';
export const DELETE_PICTURE_REQUEST = 'DELETE_PICTURE_REQUEST';

export const FETCH_PICTURE_REQUEST = 'FETCH_PICTURE_REQUEST';
export const FETCH_PICTURE_FAILURE = 'FETCH_PICTURE_FAILURE';
export const RECEIVE_PICTURE_DATA = 'RECEIVE_PICTURE_DATA';

export const ADD_FOLDER_SUCCESS = 'ADD_FOLDER_SUCCESS';
export const ADD_FOLDER_FAILURE = 'ADD_FOLDER_FAILURE';
export const ADD_FOLDER_REQUEST = 'ADD_FOLDER_REQUEST';

export const DELETE_FOLDER_SUCCESS = 'DELETE_FOLDER_SUCCESS';
export const DELETE_FOLDER_FAILURE = 'DELETE_FOLDER_FAILURE';
export const DELETE_FOLDER_REQUEST = 'DELETE_FOLDER_REQUEST';

export const FETCH_FOLDER_REQUEST = 'FETCH_FOLDER_REQUEST';
export const FETCH_FOLDER_FAILURE = 'FETCH_FOLDER_FAILURE';
export const RECEIVE_FOLDER_DATA = 'RECEIVE_FOLDER_DATA';

export const ADD_PICTURE_FOLDER_REQUEST = 'ADD_PICTURE_FOLDER_REQUEST';
export const ADD_PICTURE_FOLDER_SUCCESS = 'ADD_PICTURE_FOLDER_SUCCESS';
export const ADD_PICTURE_FOLDER_FAILURE = 'ADD_PICTURE_FOLDER_FAILURE';

export const ADD_PICTURE_TAG_REQUEST = 'ADD_PICTURE_TAG_REQUEST';
export const ADD_PICTURE_TAG_SUCCESS = 'ADD_PICTURE_TAG_SUCCESS';
export const ADD_PICTURE_TAG_FAILURE = 'ADD_PICTURE_TAG_FAILURE';

export const DELETE_PICTURE_FOLDER_REQUEST = 'DELETE_PICTURE_FOLDER_REQUEST';
export const DELETE_PICTURE_FOLDER_SUCCESS = 'DELETE_PICTURE_FOLDER_SUCCESS';
export const DELETE_PICTURE_FOLDER_FAILURE = 'DELETE_PICTURE_FOLDER_FAILURE';

export const DELETE_PICTURE_TAG_REQUEST = 'DELETE_PICTURE_TAG_REQUEST';
export const DELETE_PICTURE_TAG_SUCCESS = 'DELETE_PICTURE_TAG_SUCCESS';
export const DELETE_PICTURE_TAG_FAILURE = 'DELETE_PICTURE_TAG_FAILURE';

export const SET_APP_LOADED = 'SET_APP_LOADED';

export const CHANGE_LANG_SUCCESS = 'CHANGE_LANG_SUCCESS';
export const CHANGE_LANG_REQUEST = 'CHANGE_LANG_REQUEST';

export const CHANGE_LOCATION_SUCCESS = 'CHANGE_LOCATION_SUCCESS';
export const CHANGE_LOCATION_REQUEST = 'CHANGE_LOCATION_REQUEST';

export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';
